const char* fragmentShaderCode = "#version 410 core\n"
			"out vec4 FragColor;\n"
			"in vec2 TexCoord;"
			"uniform vec3 objectColor;"
			"uniform vec3 lightColor;"
			"uniform sampler2D texture1;"
			"uniform sampler2D texture2;"
			"void main() {"
			"	FragColor = mix(texture(texture1, TexCoord), texture(texture2, TexCoord), 0.5);"
			"	float ambientStrength = 0.3;"
			"   vec3 ambient = ambientStrength * lightColor;"
			"   vec3 result = ambient * objectColor;"
			"   FragColor *= vec4(result, 1.0);"
			"}\0";
